### PR TITLE
updating fdk docs in parallel to mikes fdk repo PR

### PR DESCRIPTION
**Pull request by carimura**
- adding  a few small things from the fdk repo that shouldn't be over there
- i like big heads
- a little more "what the heck is this"

goes along with: https://github.com/fnproject/fdk-java/pull/190

### CODE REVIEW

**Comment by michael-w-williams** [comment]
So why are we updating this page?  Shouldn't we just delete it?

**Comment by carimura** [comment]
this is the docs repo. Isn't this where you want the FDK docs? I'm confused.

**Comment by carimura** [comment]
ok new strategy --- nuking FDK folders here as they are just duplicates. All dev-facing stuff should be in tutorials.

Don't merge yet just so we can make sure nothing critical is missed in the tutorials or other places of docs repo. Doubtful since this is all old, but maybe.

**Comment by carimura** [comment]
ok closing this in favor of keeping the fdk docs in ... docs repo.

**Pull request closed without merging**
