### PR TITLE
Updated CLI Ref cards. Added links to new how-to's including init image

### PR DESCRIPTION
**Pull request by michael-w-williams**
Ran script on ref cards. No changes in the help text that Git found. Added links to the new How-to's on init image and creating functions. Added small version number below command list indicating which Fn version was used to create the cards.

### CODE REVIEW

**Comment by michael-w-williams** [comment]
Forgot to add the updated Ruby script. Added a regex function to extract the version number so it can be printed when the docs are generated. Only putting in the summary now. Could be put on each ref card if we want.

**Comment by sachin-pikle** [comment]
Strange but I don't see fn invoke in the list of fn commands here?

**Comment by michael-w-williams** [comment]
It is not in the list, must have missed it.  Will add it.

**Comment by michael-w-williams** [comment]
Changes made. I think we should merge this and start a new branch if we want more changes.

**Pull request merged**
