### PR TITLE
improved docs

### PR DESCRIPTION
**Pull request by 0xflotus**

### CODE REVIEW

**Comment by 0xflotus** [comment]
I will sign the OCA asap.

**Comment by michael-w-williams** [comment]
Thanks on the OCA.

Heads up. In regard to the READMEs for the FDKs. I'm in the process of redoing those. Just committed the first one to FDK-Java. See: https://github.com/fnproject/docs/tree/master/fdks/fdk-java. So the goal will be to make the other FDK README pages look more like the Java one. Thanks for the fixes.

**Comment by rdallman** [comment]
hey @0xflotus we've processed your CLA now but the bot is not working, did you happen to sign the CLA with a different email than one that is on your github account? thanks for patch, hoping to get this landed.

**Comment by carimura** [comment]
i think it's a typo on our OCA page.... stand by

**Comment by carimura** [comment]
fixed. may take a few hours to clear up. unsure if a kick is necessary. let's wait and see.

**Pull request merged**
